### ISSUE TITLE
guard() not being called with context

### ISSUE THREAD

**Issue by andrewn** [matthewp/react-robot#10] opened 2020-02-07 13:24 UTC
Hi, I'm not sure if I've misunderstood the behaviour of `guard` and context but I'd expect `guard()` to be called with the `initialContext` of a machine I've created.

I've created a small test case with three states: `init`, `loading` and `showing`. I'd like to use some flag passed into the initial context to immediately transition from `init` to either `loading` or `showing`.

The code I'm using is [running here](https://codesandbox.io/s/react-robot-guard-not-receiving-context-cgcyi) and copied below.

Logging the first argument of `guard` shows an empty object being passed in. I'd expect this to be the initial context that I've passed to `useMachine`. But, maybe I've misunderstood how it's supposed to work?

```js
import React from "react";
import { createMachine, guard, immediate, state } from "robot3";
import { useMachine } from "react-robot";

const stateMachine = createMachine("init", {
  init: state(
    immediate(
      "loading",
      guard(ctx => {
        console.log("guard/loading", ctx);
        return !ctx.hasThing;
      })
    ),
    immediate(
      "showing",
      guard(ctx => {
        console.log("guard/showing", ctx);
        return ctx.hasThing;
      })
    )
  ),
  loading: state(),
  showing: state()
});

export default function App() {
  const initialContext = { hasThing: true };
  const [current, send] = useMachine(stateMachine, initialContext);

  return current.name;
}
```

**Comment by matthewp** [comment] 2020-02-07 13:52
Hi! Thanks for filing an issue on this. It's very likely a bug, not sure if it's a bug with react-robot or with robot itself. Can you try doing this *without* using an immediate? I wonder if the immediate is where the problem is vs. something else.

**Comment by matthewp** [comment] 2020-02-07 14:21
[createMachine](https://thisrobot.life/api/createMachine.html#context) takes a 3rd argument which is the context creating function. If you use this `ctx => ctx` it will work:

```js
const machine = createMachine("init", states, ctx => ctx);
```

**Comment by matthewp** [comment] 2020-02-07 14:21
Closing, let me know if I misunderstood the problem.

**Closed by matthewp** 2020-02-07 14:21 UTC

**Comment by andrewn** [comment] 2020-02-07 14:28
Yep, that makes it behave as intended. Thanks!

Is there a reason why that isn't the default behaviour when no context function is provided to `createMachine`?

**Comment by matthewp** [comment] 2020-02-07 14:53
Yes, because providing a context at all is optional. So if the default was `ctx => ctx` then you'd get an undefined context by default which I don't think is the right choice. Maybe the default should be `ctx => ctx || {}` but that would increase the build size. I'd be more ok with changing this for the hooks though, happy to discuss in https://github.com/matthewp/robot-hooks if you want to start an issue there.
